// lib/topics/topics-db.ts
// AUTO-GENERATED by scripts/generate-topics.ts
// Generated: 2025-10-18T16:38:35.044Z

import { Topic } from './types';

export const TOPICS_DB: Record<string, Topic> = {
  'quantum-computing': {
    slug: 'quantum-computing',
    title: 'Quantum Computing',
    metaDescription: `Understand quantum computing simply. Learn how quantum computers work using qubits, superposition, and entanglement. Explained at 3 levels.`,
    category: 'Technology',
    difficulty: 'Advanced',
    searchVolume: 12000,
    explanations: {
      '5yo': `Did you know that computers can be super tiny, almost like magic, when they work in a special way? That’s what quantum computers do!

Imagine you have a toy box filled with blocks. A regular computer is like a friend who can only pick one block at a time to play with. But a quantum computer is like a magical friend who can hold lots of blocks at once and play with them all together! This helps it solve puzzles much faster.

Here’s the fun part:
- Regular computers use bits, like tiny switches that can be either off (0) or on (1).
- Quantum computers use qubits, which can be both off and on at the same time, kind of like a spinning coin that’s both heads and tails until you catch it!
- This special ability helps them tackle really hard problems much quicker.

Isn’t that amazing? It’s like having a superhero computer! Want to know more about how these magical qubits work?`,
      normal: `Quantum computing is like having a supercharged computer that can solve certain problems way faster than regular computers. It's not just about being faster; it’s about thinking differently.

Imagine a regular computer as a really efficient librarian. It can find answers in a huge library, but it looks through the books one by one. Now, picture a quantum computer as a magical librarian who can open every book at once and read all the pages simultaneously. This is possible thanks to something called "quantum bits" or "qubits," which can be in multiple states at the same time, unlike regular bits that are either a 0 or a 1.

Here’s how it works in simple terms:

1. **Qubits:** Regular computers use bits (0s and 1s), while quantum computers use qubits, which can be both 0 and 1 at the same time.
2. **Superposition:** This ability to be in multiple states allows quantum computers to process a lot of possibilities at once.
3. **Entanglement:** Qubits can be linked together, so the state of one qubit can depend on another, even if they’re far apart. This creates a powerful connection that boosts processing power.
4. **Interference:** Quantum computers can use interference to amplify the right answers and cancel out the wrong ones.

This matters because quantum computers could tackle complex problems in fields like medicine, cryptography, and materials science much faster than current computers ever could. 

Does that make sense? Want to dive deeper into any part of it, like how qubits work?`,
      advanced: `Most people think quantum computing is just a faster version of classical computing, but it fundamentally reshapes how we process information. 

Imagine a library where each book represents a possible solution to a problem. A classical computer is like a librarian who checks each book one at a time, while a quantum computer acts like a librarian who can simultaneously check multiple books due to its unique properties. This simultaneous processing stems from quantum bits, or qubits, which can exist in multiple states at once—a phenomenon known as superposition.

Here's how it works:

1. **Qubits vs. Bits**: Classical bits are binary, representing either 0 or 1. Qubits can represent both 0 and 1 simultaneously, thanks to superposition.
2. **Entanglement**: Qubits can be entangled, meaning the state of one qubit is directly related to the state of another, regardless of distance. This correlation allows for complex computations.
3. **Interference**: Quantum algorithms utilize interference to amplify the probability of correct solutions while canceling out incorrect ones, akin to waves reinforcing and canceling each other.
4. **Parallelism**: Because of superposition and entanglement, quantum computers can explore many possible solutions at once, dramatically accelerating certain computations, especially in fields like cryptography and optimization.

However, this isn't without challenges. Quantum systems are highly sensitive to their environments, leading to errors in calculations—a phenomenon known as decoherence. Researchers are actively developing error-correction methods to address this.

The implications are profound: quantum computing has the potential to solve problems that are currently intractable for classical computers, such as factoring large numbers, simulating quantum systems, and optimizing complex systems. Yet, practical and scalable quantum computers are still in development, and ongoing debates continue about their long-term capabilities and applications.

If you're intrigued, we could delve into specific algorithms like Shor's and Grover's, or explore how quantum computing challenges existing cryptographic systems.`,
    },
    relatedTopics: ["superposition","qubits","quantum-mechanics","cryptography","computing"],
    keywords: ["quantum computing","qubits","superposition","quantum mechanics","quantum computers explained"],
    lastUpdated: '2025-10-18T16:38:35.044Z',
  },

  'blockchain': {
    slug: 'blockchain',
    title: 'Blockchain',
    metaDescription: `Learn how blockchain works in simple terms. Understand distributed ledgers, cryptography, and why blockchain powers Bitcoin and cryptocurrencies.`,
    category: 'Technology',
    difficulty: 'Intermediate',
    searchVolume: 45000,
    explanations: {
      '5yo': `Did you know that there’s a special way to keep track of things that makes it super safe and hard to change? That’s what blockchain is like!

Imagine a big notebook where you and your friends write down all the fun games you’ve played together. Each page in the notebook is like a block, and once you write something, it can’t be erased. Each page is linked to the one before it, making a chain of all your games!

Here’s how it works:
- Each block holds information, like a record of a game.
- Everyone can see the notebook, so no one can cheat or change what’s written.
- Once you write on a page, it’s there forever, just like a promise!

This is cool because it helps people trust each other, even if they don’t know each other very well. Want to know how people use blockchain for things like money or art?`,
      normal: `Blockchain isn’t just a fancy tech term; it’s like a digital notebook that everyone can read but no one can change. Imagine a group of friends passing around a diary where they write down everything they do together. Once something’s written in there, it can’t be erased or edited.

In the digital world, a blockchain works the same way. It records transactions in a series of blocks that are linked together, creating a chain. Each block contains a list of transactions and a unique code that connects it to the previous block. This makes it super secure because if someone tries to change one block, it would mess up the entire chain, and everyone would notice.

Here’s how it works:

1. Someone makes a transaction (like sending money).
2. The transaction is grouped with others into a block.
3. Computers (called nodes) on the network check if the transaction is valid.
4. Once verified, the block is added to the chain, and everyone’s copy is updated.
5. The transaction is now permanent and transparent.

Why does this matter? It means we can trust transactions without needing a middleman, like a bank. This opens up a lot of possibilities, from secure payments to tracking products in supply chains.

Does that make sense? Want to dive deeper into how the verification process works?`,
      advanced: `Many people assume blockchain is just a technology for cryptocurrencies, but its implications extend far beyond that. Imagine a digital ledger that is not stored in a single location but is distributed across a vast network of computers, ensuring both transparency and security.

Think of blockchain like a public library where every book (or block) contains a record of transactions. Each time someone borrows a book, that action is recorded in a new book, and once it's full, it gets added to the library's archive (or chain). The unique twist is that every book contains a reference to the previous one, creating a secure and unalterable chain of records. This structure means that once a transaction is recorded, it cannot easily be altered or deleted, enhancing trust among participants.

Here’s how it works in detail:

1. **Decentralization**: Unlike traditional databases that are managed by a single entity, blockchain operates on a distributed network of nodes (computers). Each node has a copy of the entire blockchain, making the system resilient to failures or attacks.

2. **Consensus Mechanisms**: To validate new transactions, all nodes must agree on their legitimacy. This is achieved through consensus algorithms like Proof of Work (PoW) or Proof of Stake (PoS), which ensure that only valid transactions are added to the blockchain.

3. **Cryptographic Security**: Each block contains a cryptographic hash of the previous block, along with its own data and timestamp. This ensures that altering any block would require recalculating all subsequent hashes, making tampering nearly impossible.

4. **Transparency and Immutability**: Since the blockchain is public (in many cases), anyone can view the transactions. This transparency, combined with the immutability of the records, fosters trust among users.

5. **Smart Contracts**: Beyond simple transactions, blockchains can automate processes through smart contracts—self-executing contracts with the terms of the agreement directly written into code. This allows for complex transactions without intermediaries.

6. **Applications Beyond Currency**: While cryptocurrencies like Bitcoin are the most well-known application, blockchain technology is being explored in various fields, from supply chain management to healthcare, voting systems, and digital identity verification.

7. **Current Limitations**: Despite its potential, blockchain faces challenges such as scalability, energy consumption (especially with PoW), and regulatory concerns. The debate continues over how to address these issues while maintaining the core benefits of decentralization and security.

As the technology matures, exploring adjacent topics like decentralized finance (DeFi) or non-fungible tokens (NFTs) could provide further insights into the transformative potential of blockchain.`,
    },
    relatedTopics: ["bitcoin","cryptocurrency","cryptography","distributed-systems","smart-contracts"],
    keywords: ["blockchain","distributed ledger","bitcoin","cryptocurrency","blockchain explained"],
    lastUpdated: '2025-10-18T16:38:35.044Z',
  },

  'machine-learning': {
    slug: 'machine-learning',
    title: 'Machine Learning',
    metaDescription: `Discover how machine learning works. Understand AI, neural networks, and how computers learn from data. Explained simply.`,
    category: 'Technology',
    difficulty: 'Intermediate',
    searchVolume: 89000,
    explanations: {
      '5yo': `Did you know that machines can learn from examples just like you do? That's what machine learning is all about!

Imagine teaching a puppy to sit. You show it what "sit" means by giving it a treat every time it does the right thing. The more you practice, the better the puppy gets at sitting when you ask!

Machine learning works in a similar way:
- First, you give the computer lots of examples (like pictures of cats and dogs).
- Then, it starts to notice patterns (like cats have pointy ears and dogs have floppy ears).
- Finally, it can guess what a new picture is based on what it has learned!

It's super cool because it helps computers do things like recommend your favorite cartoons or even help doctors find out how to make people feel better!

Doesn't that sound fun? Want to know more about how machines can learn from different kinds of examples?`,
      normal: `Machine learning is like teaching a computer to learn from experience, much like how we learn from practice.

Imagine you’re teaching a dog new tricks. The more you train it, the better it gets at understanding commands. In machine learning, instead of a dog, you have a computer program, and instead of commands, you give it data. The program looks at patterns in the data and improves its performance over time without being explicitly programmed for every single task.

Here’s how it works:

1. **Data Collection**: You gather a lot of examples (like photos of cats and dogs).
2. **Training**: You feed these examples into the program so it can learn the difference between a cat and a dog.
3. **Model Creation**: The program creates a model, which is like a set of rules based on what it learned.
4. **Testing**: You show it new examples it hasn’t seen before to see if it can correctly identify them.
5. **Improvement**: If it gets things wrong, you can refine the model and try again.

This matters because machine learning powers so many things we use every day, like recommendations on Netflix, voice assistants like Siri, and even self-driving cars. It helps computers make decisions or predictions based on data, and that can save time and improve accuracy.

Does that make sense? Want me to dive deeper into how the training process works or how it’s used in real life?`,
      advanced: `Many people think of machine learning as just a subset of artificial intelligence focused on data analysis. However, it's much more nuanced, representing a shift in how we approach problem-solving and pattern recognition.

Imagine a chef who learns to cook. Instead of following a rigid recipe, they taste and adjust based on feedback. Machine learning operates similarly, where algorithms learn from data rather than following explicit instructions. This process is akin to a complex network of chefs refining their skills based on experience, adjusting flavors, and improving dishes over time.

Here's how the mechanism works:

1. **Data Input**: Machine learning begins with data, which can be anything from images to text or numerical values.
2. **Model Selection**: Algorithms, or models, are chosen based on the type of problem—supervised learning for labeled data or unsupervised learning for patterns in unlabeled data.
3. **Training Process**: The model is trained using historical data, adjusting its parameters to minimize errors in predictions or classifications.
4. **Validation**: The model is then validated on a separate dataset to ensure it generalizes well to new, unseen data.
5. **Feedback Loop**: Continuous learning can occur through new data, allowing the model to adapt and improve over time.
6. **Deployment**: Once validated, the model can be deployed for real-world applications, such as recommendations or predictions.
7. **Performance Monitoring**: Ongoing evaluation is crucial to maintain accuracy and adjust as new data or conditions arise.

Understanding machine learning involves recognizing its implications across various fields, from healthcare to finance, and appreciating the debates surrounding ethics, bias, and transparency. While we know that machine learning can uncover patterns and drive decision-making, ongoing discussions revolve around interpretability and accountability in algorithms.

If you're interested, we could explore specific types of machine learning, such as reinforcement learning or deep learning, or delve into the ethical considerations of AI applications.`,
    },
    relatedTopics: ["artificial-intelligence","neural-networks","deep-learning","data-science","algorithms"],
    keywords: ["machine learning","AI","neural networks","artificial intelligence","ML explained"],
    lastUpdated: '2025-10-18T16:38:35.044Z',
  },

  'photosynthesis': {
    slug: 'photosynthesis',
    title: 'Photosynthesis',
    metaDescription: `Learn how plants make food from sunlight. Understand photosynthesis, chlorophyll, and why plants are green. Simple explanations.`,
    category: 'Science',
    difficulty: 'Beginner',
    searchVolume: 67000,
    explanations: {
      '5yo': `Did you know that plants are like little chefs making their own food? That’s what photosynthesis is all about!

It's like when you mix ingredients to bake cookies. Plants take sunlight, water, and air to create their food! They use their leaves like a kitchen to cook up a meal.

Here’s how it works:
- The sun shines on the leaves, giving them energy.
- The plant drinks up water from the ground through its roots.
- The plant takes in air (the part we call carbon dioxide) through tiny holes in its leaves.

Then, with all these ingredients, the plant makes food to grow and stay healthy, and it gives off oxygen, which we breathe!

Isn’t it amazing how plants can do that? Want to learn what happens to the food they make?`,
      normal: `Photosynthesis is like a recipe that plants use to make their own food using sunlight. Imagine you’re baking a cake: you need ingredients, an oven, and a bit of time. Plants do something similar but instead of flour and sugar, they use sunlight, water, and carbon dioxide.

Here’s how it all comes together:

1. **Sunlight**: Plants have special cells that capture sunlight, like solar panels.
2. **Water and Carbon Dioxide**: They take in water through their roots and carbon dioxide from the air through tiny openings in their leaves.
3. **Making Food**: Using the sunlight’s energy, plants combine water and carbon dioxide to create glucose, which is a type of sugar they use for energy.
4. **Oxygen Release**: As a bonus, they release oxygen into the air, which we need to breathe.

This process is super important because it’s how plants grow and produce the oxygen we need. Without photosynthesis, life on Earth would be very different!

Does that make sense? Want me to explain any part differently?`,
      advanced: `Most people view photosynthesis simply as a plant’s way of making food, but it’s actually a complex biochemical process that underpins the entire ecosystem.

Imagine photosynthesis as a solar-powered factory. Plants, like factories, take raw materials and transform them into valuable products. In this case, the factory uses sunlight, carbon dioxide, and water to produce glucose (a form of sugar) and oxygen. 

Here’s how it works:

1. **Light Absorption:** Chlorophyll, the green pigment in leaves, absorbs sunlight. This energy is crucial for driving the photosynthesis process.
  
2. **Water Splitting:** The absorbed light energy splits water molecules (H₂O) into hydrogen and oxygen. The oxygen is released as a byproduct into the atmosphere.

3. **Carbon Fixation:** Carbon dioxide (CO₂) from the air enters the plant through small openings called stomata. Using energy from the light reactions, the hydrogen from the split water molecules combines with carbon dioxide to form glucose (C₆H₁₂O₆) through a series of reactions known as the Calvin cycle.

4. **Energy Storage:** The glucose produced serves as an energy source for the plant, fueling growth and metabolism. It can also be stored for later use or converted into other substances, like starch.

Where the analogy breaks down: While factories create products, the energy transformation in photosynthesis isn’t just a simple conversion; it involves intricate biochemical pathways and enzyme interactions.

The implications of photosynthesis are profound. It not only sustains the plant itself but also forms the foundation of food chains across ecosystems. Additionally, it plays a critical role in regulating atmospheric CO₂ levels, thus influencing climate and environmental health. 

Current research continues to explore how we can enhance photosynthesis to improve agricultural productivity or even harness it for biofuel production. Would you like to dive deeper into the Calvin cycle or the role of photosynthesis in global carbon cycles?`,
    },
    relatedTopics: ["chlorophyll","plants","biology","cellular-respiration","ecology"],
    keywords: ["photosynthesis","plants","chlorophyll","how plants make food","photosynthesis explained"],
    lastUpdated: '2025-10-18T16:38:35.044Z',
  },

  'bitcoin': {
    slug: 'bitcoin',
    title: 'Bitcoin',
    metaDescription: `Understand Bitcoin simply. Learn how cryptocurrency works, blockchain technology, and why Bitcoin is digital money.`,
    category: 'Finance',
    difficulty: 'Intermediate',
    searchVolume: 124000,
    explanations: {
      '5yo': `Did you know there’s a kind of money that you can’t hold in your hand, like a toy that only exists in a video game? That’s what Bitcoin is!

Imagine you have a special kind of sticker that you can trade with your friends. Each sticker is unique, and when you trade them, everyone can see who has what sticker. Bitcoin works like that! Instead of stickers, it’s digital money that people can send to each other using computers.

Here’s how it works:
- Bitcoin is stored on computers, not in banks like regular money.
- People use their computers to send and receive Bitcoin, and everyone can see these trades, which keeps it safe.
- It’s special because there’s only a limited amount, just like how you might only have a few rare stickers.

Isn't it cool that money can be digital and still be valuable? Want to know how people get Bitcoin?`,
      normal: `Bitcoin isn't just digital money; it's more like a global ledger that everyone can see, but nobody can change. Imagine it as a shared notebook where everyone records transactions, and each page is locked in place once it's filled out.

Here’s how it works:

1. You want to send Bitcoin to someone, like paying a friend.
2. You announce your transaction to the network, like shouting it out in a room full of people.
3. Thousands of computers in the network check to ensure you actually have the Bitcoin and that the transaction is valid.
4. Once verified, your transaction gets added to the permanent record, which is the blockchain.
5. Now, everyone has a copy of that record, showing you sent the Bitcoin.

This matters because it allows you to send money directly to someone without needing a bank or middleman. It makes transactions faster and often cheaper.

Does that make sense? Want to dive deeper into how the network verifies these transactions?`,
      advanced: `Many people think of Bitcoin as just a digital currency, but it’s much more than that; it’s a decentralized financial system that challenges traditional banking and currency models.

Imagine a global ledger, like a gigantic spreadsheet, where every transaction is recorded and visible to everyone, but no single entity controls it. This ledger is maintained through a technology called blockchain, which consists of a series of blocks containing transaction data, linked together in a secure chain. Each block is verified by a network of computers, known as nodes, which ensures that the information is accurate and tamper-proof.

Here’s how Bitcoin operates:

1. **Decentralization**: Unlike government-issued currencies, Bitcoin is not controlled by any central authority. This reduces the risk of manipulation or inflation caused by excessive printing of money.
  
2. **Mining**: New bitcoins are created through a process called mining, where powerful computers solve complex mathematical problems to validate transactions. Once solved, miners add a new block to the blockchain and are rewarded with bitcoin.

3. **Supply Limit**: There will only ever be 21 million bitcoins, which introduces scarcity similar to precious metals. This capped supply can influence its value over time.

4. **Peer-to-Peer Transactions**: Bitcoin allows users to send and receive payments directly without intermediaries like banks, reducing transaction fees and increasing transaction speed.

5. **Security**: Each transaction is encrypted and linked to previous transactions, making it very difficult to alter past records. This enhances trust and transparency.

6. **Volatility**: The price of Bitcoin can fluctuate widely due to market demand, speculation, and regulatory news, which can lead to significant investment risks.

7. **Legal and Regulatory Framework**: The status of Bitcoin varies by country, with some embracing it while others impose strict regulations or outright bans.

The implications of Bitcoin extend beyond mere currency; it raises questions about the future of finance, privacy, and central authority. While Bitcoin has the potential to revolutionize transactions and value storage, debates about its environmental impact, scalability, and regulatory challenges are ongoing.

If you're curious, we could explore concepts like the technological underpinnings of blockchain or the implications of decentralized finance (DeFi) further.`,
    },
    relatedTopics: ["blockchain","cryptocurrency","mining","digital-currency","decentralization"],
    keywords: ["bitcoin","cryptocurrency","digital currency","blockchain","BTC explained"],
    lastUpdated: '2025-10-18T16:38:35.044Z',
  },

  'inflation': {
    slug: 'inflation',
    title: 'Inflation',
    metaDescription: `Learn what inflation means for your money. Understand rising prices, purchasing power, and economic impact explained simply.`,
    category: 'Finance',
    difficulty: 'Beginner',
    searchVolume: 156000,
    explanations: {
      '5yo': `Did you know that inflation is like when your favorite candy suddenly costs more than it used to? It’s a way of saying that things are getting more expensive!

Imagine you have a piggy bank with some money in it to buy candy. If one day a candy bar costs \$1, but later it costs \$2, that means you need more money to buy the same candy. That’s inflation!

Here’s how it works:
- When more money is around, people want to buy more things.
- If there are not enough things to buy, prices go up.
- So, you need more of your piggy bank money to get the same treats!

This is important because it helps us understand how our money works and why we might need to save a little more for our favorite snacks!

What’s your favorite candy? Have you ever noticed its price change?`,
      normal: `Inflation isn't just about prices going up; it's more like the value of your money slowly shrinking over time.

Imagine you have a favorite candy bar that costs \$1 today. If inflation is happening, that same candy bar might cost \$1.10 next year. So, your dollar doesn't buy as much as it used to. 

Here’s how inflation works:

1. **More Money in Circulation**: When the government prints more money or when banks lend more, there's more money available to buy things.
2. **Increased Demand**: If lots of people want to buy the same stuff but there’s only so much of it, prices go up.
3. **Cost of Production**: If it costs more to make goods (like higher wages or raw materials), companies raise prices to cover those costs.

Why does this matter? If your money loses value, you can’t buy as much with it, which affects your savings and spending power. 

Does that make sense? Want me to explain how inflation impacts things like savings or investments?`,
      advanced: `Most people associate inflation solely with rising prices, but it’s a more nuanced economic phenomenon that reflects the decrease in purchasing power of money over time.

Think of inflation as a balloon expanding: as more air is added, the balloon grows larger, but the space inside becomes less substantial. In economic terms, when the money supply increases without a corresponding increase in the availability of goods and services, the value of each individual unit of currency diminishes. This leads to higher prices.

Here’s the mechanism at play:

1. **Money Supply Growth**: Central banks may increase the money supply to stimulate the economy, which, in theory, encourages spending and investment.
2. **Demand-Pull Inflation**: If consumer demand grows faster than supply, prices rise because more money chases fewer goods.
3. **Cost-Push Inflation**: If production costs (like wages or raw materials) rise, companies pass these costs onto consumers, leading to increased prices.
4. **Expectations**: If businesses and consumers expect inflation, they may raise prices and wages preemptively, creating a self-fulfilling cycle.
5. **Currency Value**: As inflation persists, the currency's purchasing power erodes, meaning it takes more money to buy the same goods and services.
6. **Impact on Interest Rates**: Central banks often raise interest rates to combat high inflation, which can slow economic growth by making borrowing more expensive.
7. **Global Considerations**: Inflation can also be influenced by global factors; for instance, supply chain disruptions or geopolitical tensions can affect prices across countries.

The deeper implications of inflation are significant. It can erode savings, disproportionately affect low-income households, and create uncertainty in investment decisions. Current debates in economics often revolve around the balance between stimulating growth and controlling inflation, especially in contexts like post-pandemic recovery.

Understanding inflation also leads to exploring related topics such as hyperinflation, deflation, and monetary policy. Would you like to delve into how central banks manage inflation or the historical consequences of hyperinflation in different economies?`,
    },
    relatedTopics: ["economics","monetary-policy","federal-reserve","purchasing-power","interest-rates"],
    keywords: ["inflation","rising prices","economics","purchasing power","inflation explained"],
    lastUpdated: '2025-10-18T16:38:35.044Z',
  }
};

// Helper function to get all topics
export function getAllTopics(): Topic[] {
  return Object.values(TOPICS_DB);
}

// Helper function to get topic by slug
export function getTopicBySlug(slug: string): Topic | null {
  return TOPICS_DB[slug] || null;
}

// Helper function to get topics by category
export function getTopicsByCategory(category: string): Topic[] {
  return getAllTopics().filter(topic => topic.category === category);
}

// Helper function to get related topics
export function getRelatedTopics(slug: string): Topic[] {
  const topic = getTopicBySlug(slug);
  if (!topic) return [];
  
  return topic.relatedTopics
    .map(relatedSlug => getTopicBySlug(relatedSlug))
    .filter((t): t is Topic => t !== null);
}

// Helper function to search topics
export function searchTopics(query: string): Topic[] {
  const lowerQuery = query.toLowerCase();
  return getAllTopics().filter(topic => 
    topic.title.toLowerCase().includes(lowerQuery) ||
    topic.keywords.some(k => k.toLowerCase().includes(lowerQuery))
  );
}